/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.smartmind.agenda;

import org.junit.jupiter.api.Test;

import net.smartmind.agenda.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
